name: GH actions on workflow_dispatch for common 1
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: build
        run: dotnet build 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: testing
        run: dotnet test
